import type {
  Organization,
  User,
  Employee,
  RoleTemplate,
  Task,
  Approval,
  Escalation,
  KnowledgeItem,
  EpisodicMemory,
  InstitutionalMemory,
  ActivityEntry,
  PerformanceMetrics,
} from '@journeyman/shared';

// ============================================
// ORGANIZATION
// ============================================
export const mockOrg: Organization = {
  id: 'org-001',
  name: 'Volund Ventures',
  slug: 'volund-ventures',
  plan: 'professional',
  settings: {},
  createdAt: '2025-12-01T00:00:00Z',
  updatedAt: '2026-02-20T00:00:00Z',
};

// ============================================
// USERS
// ============================================
export const mockUsers: User[] = [
  {
    id: 'user-001',
    orgId: 'org-001',
    email: 'zakaria@volundventures.com',
    name: 'Zakaria Sabti',
    role: 'admin',
    settings: {},
    createdAt: '2025-12-01T00:00:00Z',
  },
  {
    id: 'user-002',
    orgId: 'org-001',
    email: 'sara@volundventures.com',
    name: 'Sara Lindström',
    role: 'manager',
    settings: {},
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'user-003',
    orgId: 'org-001',
    email: 'james@volundventures.com',
    name: 'James Chen',
    role: 'member',
    settings: {},
    createdAt: '2026-01-15T00:00:00Z',
  },
];

// ============================================
// ROLE TEMPLATES
// ============================================
export const mockTemplates: RoleTemplate[] = [
  {
    id: 'tpl-001',
    name: 'Operations Coordinator',
    slug: 'operations-coordinator',
    department: 'Operations',
    description:
      'Manages daily operations, coordinates tasks across teams, handles vendor communications, and produces internal reports. Keeps the machine running smoothly.',
    capabilities: [
      { name: 'Task Management', description: 'Create, assign, and track tasks across teams', category: 'core' },
      { name: 'Process Execution', description: 'Follow and execute standard operating procedures', category: 'core' },
      { name: 'Vendor Communication', description: 'Handle vendor emails, follow-ups, and negotiations', category: 'communication' },
      { name: 'Internal Reporting', description: 'Generate daily/weekly status reports', category: 'reporting' },
      { name: 'Calendar Coordination', description: 'Schedule and manage team meetings', category: 'scheduling' },
      { name: 'Document Management', description: 'Organize and maintain shared documents', category: 'core' },
    ],
    defaultConfig: {
      communicationTone: 'professional',
      proactivityLevel: 'high',
      autonomyMode: 'semi-autonomous',
      confidenceThresholds: { execute: 0.85, recommend: 0.60, escalateBelow: 0.60 },
      languages: ['en'],
    },
    defaultIntegrations: ['google_workspace', 'slack', 'notion', 'asana'],
    taskPatterns: [
      { name: 'Daily Status Report', description: 'Compile and distribute daily operations summary', frequency: 'daily' },
      { name: 'Vendor Follow-up', description: 'Check in with vendors on pending deliverables', frequency: 'weekly' },
      { name: 'Meeting Prep', description: 'Prepare agendas and materials for team meetings', frequency: 'on_demand' },
      { name: 'Process Documentation', description: 'Update SOPs when processes change', frequency: 'event_triggered' },
    ],
    isPublic: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl-002',
    name: 'Executive Assistant',
    slug: 'executive-assistant',
    department: 'Executive',
    description:
      'Supports executives with calendar management, email triage, meeting preparation, travel coordination, and follow-up tracking. Your chief of staff, automated.',
    capabilities: [
      { name: 'Calendar Management', description: 'Schedule, reschedule, and optimize calendar', category: 'scheduling' },
      { name: 'Email Triage', description: 'Categorize, prioritize, and draft responses to emails', category: 'communication' },
      { name: 'Meeting Preparation', description: 'Research attendees, prepare briefs and agendas', category: 'research' },
      { name: 'Travel Coordination', description: 'Book flights, hotels, and manage itineraries', category: 'logistics' },
      { name: 'Follow-up Tracking', description: 'Track action items and ensure timely follow-ups', category: 'core' },
      { name: 'Document Drafting', description: 'Draft presentations, memos, and communications', category: 'communication' },
    ],
    defaultConfig: {
      communicationTone: 'formal',
      proactivityLevel: 'high',
      autonomyMode: 'semi-autonomous',
      confidenceThresholds: { execute: 0.90, recommend: 0.65, escalateBelow: 0.65 },
      languages: ['en', 'fr'],
    },
    defaultIntegrations: ['google_workspace', 'slack', 'notion'],
    taskPatterns: [
      { name: 'Morning Briefing', description: 'Compile daily schedule and priority items', frequency: 'daily' },
      { name: 'Email Triage', description: 'Process and categorize incoming emails', frequency: 'daily' },
      { name: 'Meeting Follow-ups', description: 'Send follow-up notes and track action items', frequency: 'event_triggered' },
      { name: 'Weekly Schedule Optimization', description: 'Review and optimize upcoming week schedule', frequency: 'weekly' },
    ],
    isPublic: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tpl-003',
    name: 'SDR / Outbound Sales',
    slug: 'sdr-outbound-sales',
    department: 'Sales',
    description:
      'Drives outbound sales pipeline through prospect research, personalized outreach sequences, lead qualification, and pipeline management. Revenue growth on autopilot.',
    capabilities: [
      { name: 'Prospect Research', description: 'Research companies and identify decision makers', category: 'research' },
      { name: 'Outreach Sequencing', description: 'Create and execute multi-touch outreach campaigns', category: 'communication' },
      { name: 'Lead Qualification', description: 'Score and qualify inbound/outbound leads', category: 'core' },
      { name: 'Pipeline Management', description: 'Track deals, update CRM, manage pipeline stages', category: 'core' },
      { name: 'Competitive Intelligence', description: 'Monitor competitor activity and positioning', category: 'research' },
      { name: 'Meeting Booking', description: 'Schedule discovery calls and demos', category: 'scheduling' },
    ],
    defaultConfig: {
      communicationTone: 'professional',
      proactivityLevel: 'high',
      autonomyMode: 'supervised',
      confidenceThresholds: { execute: 0.80, recommend: 0.55, escalateBelow: 0.55 },
      languages: ['en'],
    },
    defaultIntegrations: ['hubspot', 'slack', 'google_workspace', 'linkedin'],
    taskPatterns: [
      { name: 'Prospect Research Batch', description: 'Research and enrich 50 prospects per day', frequency: 'daily' },
      { name: 'Outreach Campaign', description: 'Execute personalized email/LinkedIn sequences', frequency: 'daily' },
      { name: 'Lead Scoring', description: 'Score new leads against ICP criteria', frequency: 'event_triggered' },
      { name: 'Pipeline Review', description: 'Update pipeline status and forecast', frequency: 'weekly' },
    ],
    isPublic: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

// ============================================
// AI EMPLOYEES
// ============================================
export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    orgId: 'org-001',
    name: 'Atlas',
    roleTitle: 'Operations Coordinator',
    roleTemplateId: 'tpl-001',
    department: 'Operations',
    reportsTo: 'user-002',
    reportsToName: 'Sara Lindström',
    status: 'active',
    emailAddress: 'atlas.ops@volundventures.journeyman.ai',
    phoneNumber: '+1-555-0101',
    slackUserId: 'U_ATLAS',
    config: {
      communicationTone: 'professional',
      proactivityLevel: 'high',
      autonomyMode: 'semi-autonomous',
      workingHours: { start: '08:00', end: '18:00', timezone: 'Europe/Stockholm' },
      escalationRules: [],
      confidenceThresholds: { execute: 0.85, recommend: 0.60, escalateBelow: 0.60 },
      languages: ['en', 'sv'],
      priorityHierarchy: ['urgency', 'impact', 'sender_seniority'],
    },
    autonomyScore: 0.92,
    tasksCompleted: 847,
    escalationRate: 0.03,
    hiredAt: '2026-01-15T09:00:00Z',
    onboardedAt: '2026-01-29T14:00:00Z',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-02-27T08:00:00Z',
  },
  {
    id: 'emp-002',
    orgId: 'org-001',
    name: 'Nova',
    roleTitle: 'Executive Assistant',
    roleTemplateId: 'tpl-002',
    department: 'Executive',
    reportsTo: 'user-001',
    reportsToName: 'Zakaria Sabti',
    status: 'active',
    emailAddress: 'nova.ea@volundventures.journeyman.ai',
    slackUserId: 'U_NOVA',
    config: {
      communicationTone: 'formal',
      proactivityLevel: 'high',
      autonomyMode: 'autonomous',
      workingHours: { start: '07:00', end: '19:00', timezone: 'Europe/Stockholm' },
      escalationRules: [],
      confidenceThresholds: { execute: 0.90, recommend: 0.65, escalateBelow: 0.65 },
      languages: ['en', 'fr', 'ar'],
      priorityHierarchy: ['urgency', 'sender_seniority', 'impact'],
    },
    autonomyScore: 0.96,
    tasksCompleted: 1203,
    escalationRate: 0.02,
    hiredAt: '2026-01-10T09:00:00Z',
    onboardedAt: '2026-01-20T10:00:00Z',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-02-27T07:30:00Z',
  },
  {
    id: 'emp-003',
    orgId: 'org-001',
    name: 'Apex',
    roleTitle: 'SDR Lead',
    roleTemplateId: 'tpl-003',
    department: 'Sales',
    reportsTo: 'user-002',
    reportsToName: 'Sara Lindström',
    status: 'supervised',
    emailAddress: 'apex.sales@volundventures.journeyman.ai',
    phoneNumber: '+1-555-0103',
    slackUserId: 'U_APEX',
    config: {
      communicationTone: 'professional',
      proactivityLevel: 'high',
      autonomyMode: 'supervised',
      workingHours: { start: '09:00', end: '18:00', timezone: 'America/New_York' },
      escalationRules: [],
      confidenceThresholds: { execute: 0.80, recommend: 0.55, escalateBelow: 0.55 },
      languages: ['en'],
      priorityHierarchy: ['impact', 'urgency', 'sender_seniority'],
    },
    autonomyScore: 0.71,
    tasksCompleted: 312,
    escalationRate: 0.08,
    hiredAt: '2026-02-10T09:00:00Z',
    onboardedAt: '2026-02-20T14:00:00Z',
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-27T09:00:00Z',
  },
  {
    id: 'emp-004',
    orgId: 'org-001',
    name: 'Sage',
    roleTitle: 'Research Analyst',
    department: 'Strategy',
    reportsTo: 'user-001',
    reportsToName: 'Zakaria Sabti',
    status: 'active',
    emailAddress: 'sage.research@volundventures.journeyman.ai',
    slackUserId: 'U_SAGE',
    config: {
      communicationTone: 'professional',
      proactivityLevel: 'medium',
      autonomyMode: 'semi-autonomous',
      workingHours: { start: '08:00', end: '17:00', timezone: 'Europe/Stockholm' },
      escalationRules: [],
      confidenceThresholds: { execute: 0.88, recommend: 0.65, escalateBelow: 0.65 },
      languages: ['en'],
      priorityHierarchy: ['impact', 'urgency'],
    },
    autonomyScore: 0.88,
    tasksCompleted: 456,
    escalationRate: 0.04,
    hiredAt: '2026-01-20T09:00:00Z',
    onboardedAt: '2026-02-01T10:00:00Z',
    createdAt: '2026-01-20T09:00:00Z',
    updatedAt: '2026-02-27T08:30:00Z',
  },
  {
    id: 'emp-005',
    orgId: 'org-001',
    name: 'Ember',
    roleTitle: 'Customer Success Manager',
    department: 'Customer Success',
    reportsTo: 'user-002',
    reportsToName: 'Sara Lindström',
    status: 'onboarding',
    emailAddress: 'ember.cs@volundventures.journeyman.ai',
    slackUserId: 'U_EMBER',
    config: {
      communicationTone: 'casual',
      proactivityLevel: 'high',
      autonomyMode: 'supervised',
      workingHours: { start: '09:00', end: '18:00', timezone: 'Europe/Stockholm' },
      escalationRules: [],
      confidenceThresholds: { execute: 0.85, recommend: 0.60, escalateBelow: 0.60 },
      languages: ['en', 'de'],
      priorityHierarchy: ['urgency', 'impact'],
    },
    autonomyScore: 0.45,
    tasksCompleted: 23,
    escalationRate: 0.15,
    hiredAt: '2026-02-24T09:00:00Z',
    createdAt: '2026-02-24T09:00:00Z',
    updatedAt: '2026-02-27T09:00:00Z',
  },
  {
    id: 'emp-006',
    orgId: 'org-001',
    name: 'Flux',
    roleTitle: 'Content Operations',
    department: 'Marketing',
    reportsTo: 'user-003',
    reportsToName: 'James Chen',
    status: 'paused',
    emailAddress: 'flux.content@volundventures.journeyman.ai',
    slackUserId: 'U_FLUX',
    config: {
      communicationTone: 'casual',
      proactivityLevel: 'medium',
      autonomyMode: 'semi-autonomous',
      workingHours: { start: '10:00', end: '18:00', timezone: 'America/Los_Angeles' },
      escalationRules: [],
      confidenceThresholds: { execute: 0.85, recommend: 0.60, escalateBelow: 0.60 },
      languages: ['en'],
      priorityHierarchy: ['urgency', 'impact'],
    },
    autonomyScore: 0.79,
    tasksCompleted: 189,
    escalationRate: 0.06,
    hiredAt: '2026-02-01T09:00:00Z',
    onboardedAt: '2026-02-12T14:00:00Z',
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-02-25T16:00:00Z',
  },
];

// ============================================
// TASKS
// ============================================
export const mockTasks: Task[] = [
  {
    id: 'task-001',
    orgId: 'org-001',
    employeeId: 'emp-001',
    title: 'Compile weekly operations report',
    description: 'Gather metrics from all departments and compile the weekly operations summary for leadership review.',
    source: 'scheduled',
    status: 'in_progress',
    priority: 75,
    confidenceScore: 0.94,
    assignedByName: 'Sara Lindström',
    createdAt: '2026-02-27T08:00:00Z',
    updatedAt: '2026-02-27T08:30:00Z',
    startedAt: '2026-02-27T08:05:00Z',
  },
  {
    id: 'task-002',
    orgId: 'org-001',
    employeeId: 'emp-001',
    title: 'Follow up with CloudVault on SLA renewal',
    description: 'Send follow-up email to CloudVault regarding their SLA renewal terms.',
    source: 'proactive',
    status: 'completed',
    priority: 60,
    confidenceScore: 0.91,
    createdAt: '2026-02-26T14:00:00Z',
    updatedAt: '2026-02-26T15:30:00Z',
    startedAt: '2026-02-26T14:05:00Z',
    completedAt: '2026-02-26T15:30:00Z',
  },
  {
    id: 'task-003',
    orgId: 'org-001',
    employeeId: 'emp-002',
    title: 'Prepare board meeting briefing package',
    description: 'Research attendees, compile quarterly metrics, prepare executive summary and talking points.',
    source: 'human_assigned',
    status: 'in_progress',
    priority: 90,
    confidenceScore: 0.88,
    assignedBy: 'user-001',
    assignedByName: 'Zakaria Sabti',
    dueAt: '2026-02-28T09:00:00Z',
    createdAt: '2026-02-26T10:00:00Z',
    updatedAt: '2026-02-27T07:00:00Z',
    startedAt: '2026-02-26T10:15:00Z',
  },
  {
    id: 'task-004',
    orgId: 'org-001',
    employeeId: 'emp-002',
    title: 'Reschedule Friday investor calls',
    description: 'Three investor calls need to be rescheduled due to travel changes. Find new slots that work for all parties.',
    source: 'human_assigned',
    status: 'awaiting_approval',
    priority: 70,
    confidenceScore: 0.72,
    assignedBy: 'user-001',
    assignedByName: 'Zakaria Sabti',
    createdAt: '2026-02-27T07:00:00Z',
    updatedAt: '2026-02-27T07:45:00Z',
    startedAt: '2026-02-27T07:05:00Z',
  },
  {
    id: 'task-005',
    orgId: 'org-001',
    employeeId: 'emp-003',
    title: 'Research and enrich 50 Series B fintech prospects',
    description: 'Identify and research fintech companies that recently raised Series B, enrich with decision-maker contacts.',
    source: 'scheduled',
    status: 'in_progress',
    priority: 65,
    confidenceScore: 0.86,
    createdAt: '2026-02-27T09:00:00Z',
    updatedAt: '2026-02-27T09:30:00Z',
    startedAt: '2026-02-27T09:05:00Z',
  },
  {
    id: 'task-006',
    orgId: 'org-001',
    employeeId: 'emp-003',
    title: 'Send personalized outreach to Q1 target list',
    description: 'Execute email sequence for 30 high-priority prospects with personalized messaging.',
    source: 'scheduled',
    status: 'awaiting_approval',
    priority: 80,
    confidenceScore: 0.68,
    createdAt: '2026-02-27T08:00:00Z',
    updatedAt: '2026-02-27T08:45:00Z',
    startedAt: '2026-02-27T08:05:00Z',
  },
  {
    id: 'task-007',
    orgId: 'org-001',
    employeeId: 'emp-004',
    title: 'Competitive analysis: AI workforce platforms',
    description: 'Deep dive into competitor landscape, pricing models, feature comparison, and market positioning.',
    source: 'human_assigned',
    status: 'completed',
    priority: 85,
    confidenceScore: 0.93,
    assignedBy: 'user-001',
    assignedByName: 'Zakaria Sabti',
    createdAt: '2026-02-24T10:00:00Z',
    updatedAt: '2026-02-26T16:00:00Z',
    startedAt: '2026-02-24T10:15:00Z',
    completedAt: '2026-02-26T16:00:00Z',
  },
  {
    id: 'task-008',
    orgId: 'org-001',
    employeeId: 'emp-004',
    title: 'Market sizing: MENA enterprise AI adoption',
    description: 'Research and quantify the addressable market for AI workforce solutions in MENA region.',
    source: 'human_assigned',
    status: 'in_progress',
    priority: 70,
    confidenceScore: 0.82,
    assignedBy: 'user-001',
    assignedByName: 'Zakaria Sabti',
    createdAt: '2026-02-26T11:00:00Z',
    updatedAt: '2026-02-27T09:00:00Z',
    startedAt: '2026-02-26T11:30:00Z',
  },
  {
    id: 'task-009',
    orgId: 'org-001',
    employeeId: 'emp-005',
    title: 'Complete onboarding knowledge ingestion',
    description: 'Process and learn from uploaded customer playbooks, success metrics, and communication templates.',
    source: 'event_triggered',
    status: 'in_progress',
    priority: 50,
    confidenceScore: 0.75,
    createdAt: '2026-02-24T09:00:00Z',
    updatedAt: '2026-02-27T08:00:00Z',
    startedAt: '2026-02-24T09:15:00Z',
  },
  {
    id: 'task-010',
    orgId: 'org-001',
    employeeId: 'emp-001',
    title: 'Update vendor contact database',
    source: 'proactive',
    status: 'queued',
    priority: 30,
    createdAt: '2026-02-27T09:00:00Z',
    updatedAt: '2026-02-27T09:00:00Z',
  },
  {
    id: 'task-011',
    orgId: 'org-001',
    employeeId: 'emp-002',
    title: 'Draft Q1 investor update email',
    source: 'human_assigned',
    status: 'completed',
    priority: 85,
    confidenceScore: 0.95,
    assignedBy: 'user-001',
    assignedByName: 'Zakaria Sabti',
    createdAt: '2026-02-25T09:00:00Z',
    updatedAt: '2026-02-25T14:00:00Z',
    startedAt: '2026-02-25T09:15:00Z',
    completedAt: '2026-02-25T14:00:00Z',
  },
  {
    id: 'task-012',
    orgId: 'org-001',
    employeeId: 'emp-003',
    title: 'Qualify 15 inbound leads from website',
    source: 'event_triggered',
    status: 'escalated',
    priority: 75,
    confidenceScore: 0.52,
    createdAt: '2026-02-27T07:00:00Z',
    updatedAt: '2026-02-27T07:30:00Z',
    startedAt: '2026-02-27T07:05:00Z',
  },
];

// ============================================
// APPROVALS
// ============================================
export const mockApprovals: Approval[] = [
  {
    id: 'apr-001',
    orgId: 'org-001',
    employeeId: 'emp-003',
    employeeName: 'Apex',
    employeeRole: 'SDR Lead',
    taskId: 'task-006',
    actionType: 'send_email',
    proposedAction: {
      type: 'email_sequence',
      recipientCount: 30,
      subject: 'Scaling your ops with AI teammates — worth a chat?',
      preview: 'Hi {{firstName}}, I noticed {{company}} just closed your Series B. Congrats! At JourneyMan, we help companies like yours...',
    },
    reasoning:
      'Identified 30 high-fit prospects from Q1 target list. Emails are personalized using company data and recent funding events. Confidence slightly below autonomous threshold due to new market segment (fintech).',
    confidenceScore: 0.68,
    context: { prospectCount: 30, segment: 'Fintech Series B', avgCompanySize: '50-200' },
    status: 'pending',
    expiresAt: '2026-02-28T09:00:00Z',
    createdAt: '2026-02-27T08:45:00Z',
  },
  {
    id: 'apr-002',
    orgId: 'org-001',
    employeeId: 'emp-002',
    employeeName: 'Nova',
    employeeRole: 'Executive Assistant',
    taskId: 'task-004',
    actionType: 'calendar_reschedule',
    proposedAction: {
      type: 'calendar_change',
      meetings: [
        { name: 'Investor call — Nordic Capital', from: 'Fri 10:00', to: 'Mon 14:00' },
        { name: 'Investor call — Accel Partners', from: 'Fri 14:00', to: 'Tue 10:00' },
        { name: 'Investor call — Sequoia MENA', from: 'Fri 16:00', to: 'Tue 14:00' },
      ],
    },
    reasoning:
      'Zakaria\'s Friday schedule has been cleared for travel. Found optimal slots next week that work for all parties based on timezone analysis and calendar availability. Sequoia MENA slot accounts for Dubai timezone (+4 GMT).',
    confidenceScore: 0.72,
    context: { affectedParties: 6, timezoneSpan: 'UTC-5 to UTC+4' },
    status: 'pending',
    expiresAt: '2026-02-27T18:00:00Z',
    createdAt: '2026-02-27T07:45:00Z',
  },
  {
    id: 'apr-003',
    orgId: 'org-001',
    employeeId: 'emp-001',
    employeeName: 'Atlas',
    employeeRole: 'Operations Coordinator',
    actionType: 'vendor_contract',
    proposedAction: {
      type: 'email_response',
      vendor: 'CloudVault',
      subject: 'Re: SLA Renewal Terms — Counter-proposal',
      summary: 'Proposing to accept 99.95% uptime guarantee but counter on response time (requesting 15min instead of 30min) and adding data residency clause.',
    },
    reasoning:
      'CloudVault offered standard renewal terms. Based on our past incident data, their 30min response time caused 3 escalations. Counter-proposal aligns with our infrastructure requirements doc. Data residency clause needed for EU compliance.',
    confidenceScore: 0.78,
    status: 'pending',
    createdAt: '2026-02-27T09:00:00Z',
  },
  {
    id: 'apr-004',
    orgId: 'org-001',
    employeeId: 'emp-003',
    employeeName: 'Apex',
    employeeRole: 'SDR Lead',
    actionType: 'crm_update',
    proposedAction: {
      type: 'pipeline_stage_change',
      deals: [
        { company: 'TechFlow Inc', from: 'Prospecting', to: 'Qualified' },
        { company: 'DataVault Labs', from: 'Prospecting', to: 'Qualified' },
      ],
    },
    reasoning:
      'Both companies responded positively to outreach and scheduled discovery calls. Meeting ICP criteria: >50 employees, B2B SaaS, recent funding. Moving to Qualified stage per sales playbook.',
    confidenceScore: 0.82,
    status: 'pending',
    createdAt: '2026-02-27T08:30:00Z',
  },
  {
    id: 'apr-005',
    orgId: 'org-001',
    employeeId: 'emp-005',
    employeeName: 'Ember',
    employeeRole: 'Customer Success Manager',
    actionType: 'client_communication',
    proposedAction: {
      type: 'email_draft',
      client: 'NorthStar Analytics',
      subject: 'Welcome aboard! Your onboarding journey starts here',
      summary: 'Welcome email with onboarding timeline, key contacts, and first-week milestones.',
    },
    reasoning:
      'NorthStar Analytics signed yesterday. Standard onboarding email following template with customizations based on their contract tier (Professional). Flagging for review as this is my first client communication.',
    confidenceScore: 0.61,
    status: 'pending',
    createdAt: '2026-02-27T09:15:00Z',
  },
];

// ============================================
// ESCALATIONS
// ============================================
export const mockEscalations: Escalation[] = [
  {
    id: 'esc-001',
    orgId: 'org-001',
    employeeId: 'emp-003',
    employeeName: 'Apex',
    employeeRole: 'SDR Lead',
    taskId: 'task-012',
    reason: 'Multiple leads from same enterprise account with conflicting requirements',
    context: {
      company: 'MegaCorp Industries',
      leads: [
        { name: 'VP Engineering', interest: 'AI dev tools', budget: '$200K' },
        { name: 'VP Operations', interest: 'AI workforce automation', budget: '$500K' },
        { name: 'CTO', interest: 'Full platform evaluation', budget: 'TBD' },
      ],
      conflict: 'Different stakeholders requesting different products. Enterprise account strategy needed.',
    },
    recommendation:
      'Recommend account-based approach: engage CTO as primary contact, position full platform demo covering both use cases. Suggest James Chen join as enterprise AE.',
    urgency: 'high',
    status: 'open',
    createdAt: '2026-02-27T07:30:00Z',
  },
  {
    id: 'esc-002',
    orgId: 'org-001',
    employeeId: 'emp-001',
    employeeName: 'Atlas',
    employeeRole: 'Operations Coordinator',
    reason: 'Critical vendor service degradation affecting customer deliverables',
    context: {
      vendor: 'DataStream API',
      issue: 'API response times increased 5x in last 2 hours',
      impact: '3 customer-facing data pipelines delayed',
      affectedCustomers: ['NorthStar Analytics', 'TechFlow Inc', 'Alpine Data Co'],
    },
    recommendation:
      'Immediate: switch to backup API endpoint (tested, 95% feature parity). Medium-term: escalate to DataStream account manager. I\'ve drafted the escalation email for your review.',
    urgency: 'critical',
    status: 'open',
    createdAt: '2026-02-27T08:15:00Z',
  },
  {
    id: 'esc-003',
    orgId: 'org-001',
    employeeId: 'emp-004',
    employeeName: 'Sage',
    employeeRole: 'Research Analyst',
    reason: 'Conflicting data sources for market sizing analysis',
    context: {
      report: 'MENA Enterprise AI Market Sizing',
      sources: [
        { name: 'Gartner 2025', estimate: '$4.2B' },
        { name: 'McKinsey 2026', estimate: '$7.1B' },
        { name: 'Local survey data', estimate: '$2.8B' },
      ],
      variance: '2.5x between highest and lowest estimates',
    },
    recommendation:
      'Recommend using triangulated estimate of $4.5-5.5B with methodology note explaining variance. Gartner and McKinsey differ primarily on UAE/Saudi adoption rates. Local survey likely underestimates due to sampling bias.',
    urgency: 'medium',
    status: 'open',
    createdAt: '2026-02-27T09:00:00Z',
  },
];

// ============================================
// ACTIVITY FEED
// ============================================
export const mockActivities: ActivityEntry[] = [
  {
    id: 'act-001',
    employeeId: 'emp-002',
    employeeName: 'Nova',
    action: 'task_completed',
    description: 'Completed morning briefing and sent to Zakaria',
    icon: 'check-circle',
    timestamp: '2026-02-27T07:35:00Z',
  },
  {
    id: 'act-002',
    employeeId: 'emp-001',
    employeeName: 'Atlas',
    action: 'task_started',
    description: 'Started compiling weekly operations report',
    icon: 'play',
    timestamp: '2026-02-27T08:05:00Z',
  },
  {
    id: 'act-003',
    employeeId: 'emp-003',
    employeeName: 'Apex',
    action: 'escalation_created',
    description: 'Escalated MegaCorp enterprise account conflict',
    icon: 'alert-triangle',
    timestamp: '2026-02-27T07:30:00Z',
  },
  {
    id: 'act-004',
    employeeId: 'emp-001',
    employeeName: 'Atlas',
    action: 'escalation_created',
    description: 'Critical: DataStream API degradation affecting 3 customers',
    icon: 'alert-octagon',
    timestamp: '2026-02-27T08:15:00Z',
  },
  {
    id: 'act-005',
    employeeId: 'emp-004',
    employeeName: 'Sage',
    action: 'task_started',
    description: 'Resumed MENA market sizing research',
    icon: 'search',
    timestamp: '2026-02-27T08:30:00Z',
  },
  {
    id: 'act-006',
    employeeId: 'emp-003',
    employeeName: 'Apex',
    action: 'approval_requested',
    description: 'Requesting approval to send outreach to 30 fintech prospects',
    icon: 'mail',
    timestamp: '2026-02-27T08:45:00Z',
  },
  {
    id: 'act-007',
    employeeId: 'emp-005',
    employeeName: 'Ember',
    action: 'knowledge_ingested',
    description: 'Processed 12 customer success playbook documents',
    icon: 'book-open',
    timestamp: '2026-02-27T08:00:00Z',
  },
  {
    id: 'act-008',
    employeeId: 'emp-002',
    employeeName: 'Nova',
    action: 'approval_requested',
    description: 'Requesting approval to reschedule 3 investor calls',
    icon: 'calendar',
    timestamp: '2026-02-27T07:45:00Z',
  },
  {
    id: 'act-009',
    employeeId: 'emp-001',
    employeeName: 'Atlas',
    action: 'message_sent',
    description: 'Sent SLA renewal counter-proposal to CloudVault',
    icon: 'send',
    timestamp: '2026-02-27T09:00:00Z',
  },
  {
    id: 'act-010',
    employeeId: 'emp-003',
    employeeName: 'Apex',
    action: 'task_started',
    description: 'Started researching Series B fintech prospects',
    icon: 'search',
    timestamp: '2026-02-27T09:05:00Z',
  },
];

// ============================================
// KNOWLEDGE ITEMS
// ============================================
export const mockKnowledgeItems: KnowledgeItem[] = [
  {
    id: 'ki-001',
    orgId: 'org-001',
    sourceType: 'upload',
    sourceRef: 'company-handbook-v3.pdf',
    title: 'Company Handbook v3',
    content: 'Volund Ventures company handbook covering mission, values, policies, and procedures...',
    contentHash: 'abc123',
    chunkIndex: 0,
    metadata: { author: 'HR Team', pages: 45, format: 'pdf' },
    status: 'active',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'ki-002',
    orgId: 'org-001',
    sourceType: 'upload',
    sourceRef: 'sales-playbook-2026.pdf',
    title: 'Sales Playbook 2026',
    content: 'Outbound sales strategies, ICP definitions, messaging templates...',
    contentHash: 'def456',
    chunkIndex: 0,
    metadata: { author: 'Sales Team', pages: 32, format: 'pdf' },
    status: 'active',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'ki-003',
    orgId: 'org-001',
    sourceType: 'sync',
    sourceRef: 'notion://workspace/operations-sops',
    title: 'Operations SOPs',
    content: 'Standard operating procedures for operations team...',
    contentHash: 'ghi789',
    chunkIndex: 0,
    metadata: { source: 'Notion', lastSync: '2026-02-26', docCount: 18 },
    status: 'active',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-02-26T10:00:00Z',
  },
  {
    id: 'ki-004',
    orgId: 'org-001',
    sourceType: 'upload',
    sourceRef: 'customer-success-playbook.pdf',
    title: 'Customer Success Playbook',
    content: 'Onboarding workflows, health scoring, renewal strategies...',
    contentHash: 'jkl012',
    chunkIndex: 0,
    metadata: { author: 'CS Team', pages: 28, format: 'pdf' },
    status: 'active',
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'ki-005',
    orgId: 'org-001',
    sourceType: 'manual',
    title: 'Vendor Contact Directory',
    content: 'Contact information and account details for all vendors...',
    contentHash: 'mno345',
    chunkIndex: 0,
    metadata: { entries: 47, lastUpdated: '2026-02-25' },
    status: 'active',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-25T10:00:00Z',
  },
];

// ============================================
// MEMORIES (for employee profile)
// ============================================
export const mockMemories: InstitutionalMemory[] = [
  {
    id: 'mem-001',
    orgId: 'org-001',
    employeeId: 'emp-001',
    category: 'preference',
    subject: 'Sara Lindström',
    content: 'Prefers concise bullet-point reports over detailed narratives. Likes data tables with color coding. Always wants vendor issues flagged immediately, even if minor.',
    confidence: 0.95,
    sourceCount: 23,
    metadata: {},
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-25T00:00:00Z',
  },
  {
    id: 'mem-002',
    orgId: 'org-001',
    employeeId: 'emp-001',
    category: 'pattern',
    subject: 'Weekly report timing',
    content: 'Reports sent before 9am on Mondays get acknowledged. Reports sent after lunch get less engagement. Optimal window: Monday 7:30-8:30 AM CET.',
    confidence: 0.88,
    sourceCount: 8,
    metadata: {},
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-02-24T00:00:00Z',
  },
  {
    id: 'mem-003',
    orgId: 'org-001',
    employeeId: 'emp-001',
    category: 'relationship',
    subject: 'CloudVault vendor relationship',
    content: 'Primary contact: Maria Johnson (Account Manager). Responsive via email, slow on Slack. Contract renews annually in March. Had 3 SLA incidents in 2025, all resolved within 24h.',
    confidence: 0.92,
    sourceCount: 15,
    metadata: {},
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 'mem-004',
    orgId: 'org-001',
    employeeId: 'emp-001',
    category: 'rule',
    subject: 'Vendor communication protocol',
    content: 'All vendor contract changes >$5K require Zakaria approval. SLA negotiations should reference our infrastructure requirements doc (v2.1). Always CC finance@volundventures.com on invoices.',
    confidence: 0.97,
    sourceCount: 5,
    metadata: {},
    createdAt: '2026-01-25T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
  },
  {
    id: 'mem-005',
    orgId: 'org-001',
    employeeId: 'emp-001',
    category: 'context',
    subject: 'Q1 priorities',
    content: 'Team is focused on reducing operational costs by 15%. Cloud infrastructure migration from AWS to a hybrid setup is the biggest project. Vendor renegotiations are strategic.',
    confidence: 0.90,
    sourceCount: 10,
    metadata: {},
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },
];

// ============================================
// PERFORMANCE DATA
// ============================================
export const mockPerformanceByEmployee: Record<string, PerformanceMetrics> = {
  'emp-001': {
    tasksCompletedToday: 12,
    tasksCompletedWeek: 67,
    tasksCompletedMonth: 284,
    autonomousCompletionRate: 0.92,
    escalationRate: 0.03,
    avgResponseTimeMs: 1200,
    avgResponseTimeP95Ms: 4500,
    accuracyRate: 0.98,
    managerSatisfactionScore: 4.7,
    costPerTask: 0.42,
  },
  'emp-002': {
    tasksCompletedToday: 18,
    tasksCompletedWeek: 89,
    tasksCompletedMonth: 356,
    autonomousCompletionRate: 0.96,
    escalationRate: 0.02,
    avgResponseTimeMs: 800,
    avgResponseTimeP95Ms: 3200,
    accuracyRate: 0.99,
    managerSatisfactionScore: 4.9,
    costPerTask: 0.38,
  },
  'emp-003': {
    tasksCompletedToday: 8,
    tasksCompletedWeek: 42,
    tasksCompletedMonth: 156,
    autonomousCompletionRate: 0.71,
    escalationRate: 0.08,
    avgResponseTimeMs: 2100,
    avgResponseTimeP95Ms: 8000,
    accuracyRate: 0.94,
    managerSatisfactionScore: 4.2,
    costPerTask: 0.56,
  },
  'emp-004': {
    tasksCompletedToday: 5,
    tasksCompletedWeek: 28,
    tasksCompletedMonth: 112,
    autonomousCompletionRate: 0.88,
    escalationRate: 0.04,
    avgResponseTimeMs: 3500,
    avgResponseTimeP95Ms: 12000,
    accuracyRate: 0.97,
    managerSatisfactionScore: 4.6,
    costPerTask: 0.72,
  },
  'emp-005': {
    tasksCompletedToday: 3,
    tasksCompletedWeek: 12,
    tasksCompletedMonth: 23,
    autonomousCompletionRate: 0.45,
    escalationRate: 0.15,
    avgResponseTimeMs: 4200,
    avgResponseTimeP95Ms: 15000,
    accuracyRate: 0.91,
    managerSatisfactionScore: 3.8,
    costPerTask: 0.89,
  },
  'emp-006': {
    tasksCompletedToday: 0,
    tasksCompletedWeek: 0,
    tasksCompletedMonth: 34,
    autonomousCompletionRate: 0.79,
    escalationRate: 0.06,
    avgResponseTimeMs: 1800,
    avgResponseTimeP95Ms: 6000,
    accuracyRate: 0.96,
    managerSatisfactionScore: 4.3,
    costPerTask: 0.48,
  },
};

// ============================================
// INTEGRATIONS (for settings page)
// ============================================
export const mockIntegrations = [
  { id: 'int-001', provider: 'google_workspace', name: 'Google Workspace', icon: '🔵', status: 'active' as const, description: 'Gmail, Calendar, Drive, Docs', lastSyncedAt: '2026-02-27T08:00:00Z' },
  { id: 'int-002', provider: 'slack', name: 'Slack', icon: '💬', status: 'active' as const, description: 'Messaging, channels, presence', lastSyncedAt: '2026-02-27T09:00:00Z' },
  { id: 'int-003', provider: 'notion', name: 'Notion', icon: '📝', status: 'active' as const, description: 'Docs, wikis, databases', lastSyncedAt: '2026-02-26T22:00:00Z' },
  { id: 'int-004', provider: 'hubspot', name: 'HubSpot', icon: '🧡', status: 'active' as const, description: 'CRM, deals, contacts', lastSyncedAt: '2026-02-27T07:00:00Z' },
  { id: 'int-005', provider: 'salesforce', name: 'Salesforce', icon: '☁️', status: 'expired' as const, description: 'CRM, leads, opportunities' },
  { id: 'int-006', provider: 'jira', name: 'Jira', icon: '🔷', status: 'expired' as const, description: 'Issues, sprints, boards' },
  { id: 'int-007', provider: 'microsoft_365', name: 'Microsoft 365', icon: '🟦', status: 'expired' as const, description: 'Outlook, Teams, OneDrive' },
  { id: 'int-008', provider: 'asana', name: 'Asana', icon: '🔴', status: 'expired' as const, description: 'Tasks, projects, timelines' },
  { id: 'int-009', provider: 'stripe', name: 'Stripe', icon: '💳', status: 'expired' as const, description: 'Payments, invoices, subscriptions' },
  { id: 'int-010', provider: 'zoom', name: 'Zoom', icon: '📹', status: 'expired' as const, description: 'Meetings, recordings, transcripts' },
  { id: 'int-011', provider: 'whatsapp', name: 'WhatsApp Business', icon: '💚', status: 'expired' as const, description: 'Business messaging, templates' },
  { id: 'int-012', provider: 'twilio', name: 'Twilio', icon: '📞', status: 'active' as const, description: 'Voice, SMS, phone numbers', lastSyncedAt: '2026-02-27T06:00:00Z' },
];
